### ISSUE TITLE
Avoid deprecated g_type_class_add_private

### ISSUE THREAD

**Issue by khurshid-alam** [AyatanaIndicators/ayatana-indicator-appmenu#1]
With new glib >=2.58.2, it gives lots of compilation warnings. It's better not use that.

**Comment by sunweaver** [comment]
Hi,

On  Di 19 Mär 2019 14:03:46 CET, Khurshid Alam wrote:

> With new glib >=2.58.2, it gives lots of compilation warnings. It's  
> better not use that.

ayatana-indicator-appmenu might be one of the system indicators that  
we should discuss about discontinuing.

The appmenu indicator does not really work and the guy who does  
vala-panel-appmenu found a better solution and it is reliable and  
usable cross-desktop (XFCE, MATE, etc.).

So, don't invest to much time on looking at the appmenu system indicator.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by khurshid-alam** [comment]
Sorry, I didn't know you are thinking of discontinuing. And yes vala-panel-appmenu looks like a better option. Thanks.
